global_frame: odom #safe
rolling_window: true

width: 9.0
height: 9.0
resolution: 0.05
transform_tolerance: 0.3
track_unknown_space: true
unknown_cost_value: 255

plugins:
  - {name: obstacle_layer,  type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
