# File adapted from:
# https://github.com/utexas-bwi/multi_map_navigation/blob/master/stage_multi_map_navigation/move_base_config/costmap_common_params.yaml

# Coordinate frame 
robot_base_frame: base_link
transform_tolerance: 0.3 # delay in tf data that is tolerable

# Robot description
# footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
footprint: [
  [-0.800, -0.450],
  [ 0.300, -0.450],
  [ 0.450,  0.000],
  [ 0.300,  0.450],
  [-0.800,  0.450]
]
footprint_padding: 0.050



# Default Costmap parameters
update_frequency: 5.0
publish_frequency: 2.0
resolution: 0.05


# Obstacle Global Filtering Parameters, applies to all sensors
max_obstacle_height: 0.4
min_obstacle_height: 0.08
obstacle_range: 6 #6 # max obstacle insertion range
raytrace_range: 8 #8 # max obstacle raytrace out range



# Specific Costmap configurations

static_layer:
    map_topic: map
    subscribe_to_updates: true

obstacle_layer:
  observation_sources: base_scan
  base_scan:
    data_type: LaserScan
    expected_update_rate: 0.4
    marking: true
    clearing: true

inflation_layer:
  inflation_radius: 2.0
  cost_scaling_factor: 4.0
